import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { localEnvironmentLabel, remoteShellFallbackLabel } from "./environment-labels.js";

const integrationFileName = "powershell-integration.ps1";
const bashIntegrationTemplateFileName = "bashrc.template";
const zshIntegrationTemplateFileName = "zshrc.template";
const bashDockerPromptTemplateFileName = "docker-bashrc.template";
const zshDockerPromptTemplateFileName = "docker-zshrc.template";
const integrationTokenPlaceholder = "__STACKBRIDGE_SESSION_TOKEN__";
const dockerIntegrationTokenPlaceholder = "__STACKBRIDGE_DOCKER_TOKEN__";
const localEnvironmentLabelBase64 = Buffer.from(localEnvironmentLabel, "utf8").toString("base64");
export const remoteUtf8LocaleBootstrap = 'if command -v locale >/dev/null 2>&1; then for __sb_locale in C.UTF-8 C.utf8 en_US.UTF-8 en_US.utf8; do if [ "$(LC_ALL="$__sb_locale" locale charmap 2>/dev/null)" = "UTF-8" ]; then export LANG="$__sb_locale" LC_ALL="$__sb_locale"; break; fi; done; unset __sb_locale; fi';

export function ensurePowerShellIntegration(dataDirectory: string): string {
  const shellDirectory = join(dataDirectory, "shell");
  mkdirSync(shellDirectory, { recursive: true, mode: 0o700 });
  const integrationPath = join(shellDirectory, integrationFileName);
  writeFileSync(integrationPath, powerShellIntegrationScript(), {
    encoding: "utf8",
    mode: 0o600,
  });
  writeFileSync(
    join(shellDirectory, bashIntegrationTemplateFileName),
    bashIntegrationScript(integrationTokenPlaceholder),
    { encoding: "utf8", mode: 0o600 },
  );
  writeFileSync(
    join(shellDirectory, zshIntegrationTemplateFileName),
    zshIntegrationScript(integrationTokenPlaceholder),
    { encoding: "utf8", mode: 0o600 },
  );
  writeFileSync(
    join(shellDirectory, bashDockerPromptTemplateFileName),
    bashDockerPromptScript(dockerIntegrationTokenPlaceholder),
    { encoding: "utf8", mode: 0o600 },
  );
  writeFileSync(
    join(shellDirectory, zshDockerPromptTemplateFileName),
    zshDockerPromptScript(dockerIntegrationTokenPlaceholder),
    { encoding: "utf8", mode: 0o600 },
  );
  return integrationPath;
}

export function powerShellIntegrationScript(): string {
  return String.raw`# StackBridge session-only shell integration. This file is regenerated by Core.
param([Parameter(Mandatory=$true)][string]$StackBridgeIntegrationToken)
$script:StackBridgeIntegrationToken = $StackBridgeIntegrationToken
$stackBridgeSha256 = [Security.Cryptography.SHA256]::Create()
try {
  $stackBridgeDockerTokenBytes = $stackBridgeSha256.ComputeHash(
    [Text.Encoding]::UTF8.GetBytes($StackBridgeIntegrationToken + ':docker-command-scope')
  )
} finally {
  $stackBridgeSha256.Dispose()
}
$script:StackBridgeDockerIntegrationToken = [Convert]::ToBase64String($stackBridgeDockerTokenBytes).TrimEnd('=').Replace('+', '-').Replace('/', '_')
$script:StackBridgeCommandActive = $false
$script:StackBridgeContext = [Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('${localEnvironmentLabelBase64}'))
$script:StackBridgeSeparator = " $([char]0x2192) "
$script:StackBridgeNativeSsh = Get-Command ssh.exe -ErrorAction SilentlyContinue
$script:StackBridgeNativeDocker = Get-Command docker.exe -ErrorAction SilentlyContinue
$script:StackBridgeBashTemplate = Join-Path $PSScriptRoot '${bashIntegrationTemplateFileName}'
$script:StackBridgeZshTemplate = Join-Path $PSScriptRoot '${zshIntegrationTemplateFileName}'
$script:StackBridgeDockerBashTemplate = Join-Path $PSScriptRoot '${bashDockerPromptTemplateFileName}'
$script:StackBridgeDockerZshTemplate = Join-Path $PSScriptRoot '${zshDockerPromptTemplateFileName}'

function global:Send-StackBridgeEvent {
  param([Parameter(Mandatory=$true)][hashtable]$Event)
  try {
    $json = $Event | ConvertTo-Json -Compress -Depth 8
    $bytes = [Text.Encoding]::UTF8.GetBytes($json)
    $encoded = [Convert]::ToBase64String($bytes).TrimEnd('=').Replace('+', '-').Replace('/', '_')
    [Console]::Write("$([char]27)]777;stackbridge;$script:StackBridgeIntegrationToken;$encoded$([char]7)")
  } catch {}
}

function global:prompt {
  $succeeded = $?
  if ($script:StackBridgeCommandActive) {
    Send-StackBridgeEvent @{
      type = 'commandEnd'
      cwd = [string]$executionContext.SessionState.Path.CurrentLocation
      exitCode = $(if ($succeeded) { 0 } else { 1 })
    }
    $script:StackBridgeCommandActive = $false
  }
  Send-StackBridgeEvent @{
    type = 'prompt'
    cwd = [string]$executionContext.SessionState.Path.CurrentLocation
    shell = $(if ($PSVersionTable.PSEdition -eq 'Core') { 'pwsh' } else { 'powershell' })
    user = [Environment]::UserName
  }
  $contextLine = "$([char]27)[2;38;5;111m$([char]0x256D)$([char]0x2500)[ $script:StackBridgeContext ]$([char]27)[0m"
  "$contextLine$([Environment]::NewLine)PS $($executionContext.SessionState.Path.CurrentLocation)> "
}

if (Get-Module -ListAvailable -Name PSReadLine) {
  Import-Module PSReadLine -ErrorAction SilentlyContinue
  Set-PSReadLineOption -AddToHistoryHandler {
    param([string]$line)
    Send-StackBridgeEvent @{
      type = 'commandStart'
      command = $line
      cwd = [string]$executionContext.SessionState.Path.CurrentLocation
      shell = $(if ($PSVersionTable.PSEdition -eq 'Core') { 'pwsh' } else { 'powershell' })
      user = [Environment]::UserName
    }
    $script:StackBridgeCommandActive = $true
    return $true
  }
}

function Get-StackBridgeSshShape {
  param([Parameter(Mandatory=$true)][object[]]$ArgumentList)
  $optionsWithValue = @(
    '-B', '-b', '-c', '-D', '-E', '-e', '-F', '-I', '-i', '-J', '-L', '-l',
    '-m', '-O', '-o', '-p', '-Q', '-R', '-S', '-W', '-w'
  )
  $destinationIndex = -1
  $skipNext = $false
  for ($index = 0; $index -lt $ArgumentList.Count; $index++) {
    $value = [string]$ArgumentList[$index]
    if ($skipNext) { $skipNext = $false; continue }
    if ($value -eq '--' -and $index + 1 -lt $ArgumentList.Count) {
      $destinationIndex = $index + 1
      break
    }
    if ($value.StartsWith('-')) {
      if ($optionsWithValue -contains $value) { $skipNext = $true }
      continue
    }
    $destinationIndex = $index
    break
  }
  if ($destinationIndex -lt 0) {
    return @{ Destination = $null; Interactive = $false }
  }
  return @{
    Destination = [string]$ArgumentList[$destinationIndex]
    Interactive = ($destinationIndex -eq $ArgumentList.Count - 1)
  }
}

function Install-StackBridgeRemoteShellIntegration {
  param([Parameter(Mandatory=$true)][object[]]$SshArguments)
  if (-not (Test-Path -LiteralPath $script:StackBridgeBashTemplate) -or
      -not (Test-Path -LiteralPath $script:StackBridgeZshTemplate) -or
      -not (Test-Path -LiteralPath $script:StackBridgeDockerBashTemplate) -or
      -not (Test-Path -LiteralPath $script:StackBridgeDockerZshTemplate)) {
    return $false
  }
  try {
    $bashTemplate = [IO.File]::ReadAllText($script:StackBridgeBashTemplate)
    $zshTemplate = [IO.File]::ReadAllText($script:StackBridgeZshTemplate)
    $bashScript = $bashTemplate.Replace('${integrationTokenPlaceholder}', $script:StackBridgeIntegrationToken)
    $zshScript = $zshTemplate.Replace('${integrationTokenPlaceholder}', $script:StackBridgeIntegrationToken)
    $bashEncoded = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($bashScript))
    $zshEncoded = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($zshScript))
    $dockerBashScript = [IO.File]::ReadAllText($script:StackBridgeDockerBashTemplate).Replace(
      '${dockerIntegrationTokenPlaceholder}', $script:StackBridgeDockerIntegrationToken
    )
    $dockerZshScript = [IO.File]::ReadAllText($script:StackBridgeDockerZshTemplate).Replace(
      '${dockerIntegrationTokenPlaceholder}', $script:StackBridgeDockerIntegrationToken
    )
    $dockerBashEncoded = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($dockerBashScript))
    $dockerZshEncoded = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($dockerZshScript))
    $installCommand = 'umask 077; mkdir -p "$HOME/.sbridge/shell" && printf %s ''' +
      $bashEncoded + ''' | base64 -d > "$HOME/.sbridge/shell/bashrc" && printf %s ''' +
      $zshEncoded + ''' | base64 -d > "$HOME/.sbridge/shell/.zshrc" && printf %s ''' +
      $dockerBashEncoded + ''' | base64 -d > "$HOME/.sbridge/shell/docker-bashrc" && printf %s ''' +
      $dockerZshEncoded + ''' | base64 -d > "$HOME/.sbridge/shell/docker-zshrc"'
    & $script:StackBridgeNativeSsh @SshArguments $installCommand
    return $LASTEXITCODE -eq 0
  } catch {
    return $false
  }
}

if ($script:StackBridgeNativeSsh) {
  function global:ssh {
    $sshArgs = @($args)
    $shape = Get-StackBridgeSshShape -ArgumentList $sshArgs
    $displayTarget = $shape.Destination
    if (-not $displayTarget) { $displayTarget = ($sshArgs -join ' ') }
    Send-StackBridgeEvent @{
      type = 'environmentPush'
      kind = 'ssh'
      label = "SSH: $displayTarget"
      host = [string]$displayTarget
      verified = $false
    }
    try {
      if (-not $shape.Interactive) {
        & $script:StackBridgeNativeSsh @sshArgs
        return
      }
      if (-not (Install-StackBridgeRemoteShellIntegration -SshArguments $sshArgs)) {
        & $script:StackBridgeNativeSsh @sshArgs
        return
      }
      $contextText = $script:StackBridgeContext + $script:StackBridgeSeparator + "SSH: $displayTarget"
      $contextEncoded = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($contextText))
      $launchCommand = '${remoteUtf8LocaleBootstrap}; export STACKBRIDGE_CONTEXT_B64=''' + $contextEncoded + '''; if [ "\${SHELL##*/}" = "zsh" ] && command -v zsh >/dev/null 2>&1; then export STACKBRIDGE_USER_ZDOTDIR="\${ZDOTDIR:-$HOME}"; export ZDOTDIR="$HOME/.sbridge/shell"; exec zsh -i; elif command -v bash >/dev/null 2>&1; then exec bash --rcfile "$HOME/.sbridge/shell/bashrc" -i; else exec "\${SHELL:-/bin/sh}" -i; fi'
      $interactiveArgs = @('-tt') + $sshArgs
      & $script:StackBridgeNativeSsh @interactiveArgs $launchCommand
    }
    finally { Send-StackBridgeEvent @{ type = 'environmentPop' } }
  }
}

if ($script:StackBridgeNativeDocker) {
  function global:docker {
    $dockerArgs = @($args)
    $execIndex = -1
    $skipNext = $false
    $globalOptionsWithValue = @('-c', '--context', '--config', '-H', '--host', '-l', '--log-level')
    for ($index = 0; $index -lt $dockerArgs.Count; $index++) {
      $value = [string]$dockerArgs[$index]
      if ($skipNext) { $skipNext = $false; continue }
      if ($value -eq 'exec') { $execIndex = $index; break }
      if ($value -eq 'container' -and $index + 1 -lt $dockerArgs.Count -and [string]$dockerArgs[$index + 1] -eq 'exec') {
        $execIndex = $index + 1
        break
      }
      if ($globalOptionsWithValue -contains $value) { $skipNext = $true }
      elseif (-not $value.StartsWith('-')) { break }
    }
    $interactive = $false
    $tty = $false
    if ($execIndex -ge 0) {
      $selector = $null
      $selectorIndex = -1
      for ($index = $execIndex + 1; $index -lt $dockerArgs.Count; $index++) {
        $value = [string]$dockerArgs[$index]
        if ($value -in @('-i', '--interactive')) { $interactive = $true; continue }
        if ($value -in @('-t', '--tty')) { $tty = $true; continue }
        if ($value -in @('-it', '-ti')) { $interactive = $true; $tty = $true; continue }
        if ($value -in @('-u', '--user', '-w', '--workdir', '-e', '--env', '--env-file', '--detach-keys')) { $index++; continue }
        if ($value.StartsWith('-')) { continue }
        $selector = $value
        $selectorIndex = $index
        break
      }
    }
    if ($execIndex -ge 0 -and $interactive -and $tty) {
      if ($selector) {
        Send-StackBridgeEvent @{
          type = 'environmentPush'
          kind = 'docker'
          label = "Docker: $selector"
          verified = $false
        }
      }
      $preparedArgs = $dockerArgs
      $commandIndex = $selectorIndex + 1
      if ($selectorIndex -ge 0 -and $commandIndex -eq $dockerArgs.Count - 1) {
        $commandName = [string]$dockerArgs[$commandIndex]
        $templatePath = $null
        $bootstrapCommand = $null
        if ($commandName -in @('bash', '/bin/bash')) {
          $templatePath = $script:StackBridgeDockerBashTemplate
          $bootstrapCommand = 'umask 077; runtime_dir="$(mktemp -d "\${TMPDIR:-/tmp}/stackbridge-shell.XXXXXX")" || exec "$STACKBRIDGE_TARGET_SHELL" -i; chmod 700 "$runtime_dir" || { rmdir "$runtime_dir"; exec "$STACKBRIDGE_TARGET_SHELL" -i; }; if ! printf %s "$STACKBRIDGE_PROMPT_B64" | base64 -d > "$runtime_dir/bashrc"; then rm -f "$runtime_dir/bashrc"; rmdir "$runtime_dir"; exec "$STACKBRIDGE_TARGET_SHELL" -i; fi; export STACKBRIDGE_EPHEMERAL_DIR="$runtime_dir"; unset STACKBRIDGE_PROMPT_B64; exec "$STACKBRIDGE_TARGET_SHELL" --rcfile "$runtime_dir/bashrc" -i'
        } elseif ($commandName -in @('zsh', '/bin/zsh')) {
          $templatePath = $script:StackBridgeDockerZshTemplate
          $bootstrapCommand = 'umask 077; runtime_dir="$(mktemp -d "\${TMPDIR:-/tmp}/stackbridge-shell.XXXXXX")" || exec "$STACKBRIDGE_TARGET_SHELL" -i; chmod 700 "$runtime_dir" || { rmdir "$runtime_dir"; exec "$STACKBRIDGE_TARGET_SHELL" -i; }; if ! printf %s "$STACKBRIDGE_PROMPT_B64" | base64 -d > "$runtime_dir/.zshrc"; then rm -f "$runtime_dir/.zshrc"; rmdir "$runtime_dir"; exec "$STACKBRIDGE_TARGET_SHELL" -i; fi; export STACKBRIDGE_EPHEMERAL_DIR="$runtime_dir"; unset STACKBRIDGE_PROMPT_B64; export STACKBRIDGE_USER_ZDOTDIR="\${ZDOTDIR-}"; export STACKBRIDGE_USER_ZDOTDIR_SET="\${ZDOTDIR+x}"; export ZDOTDIR="$runtime_dir"; exec "$STACKBRIDGE_TARGET_SHELL" -i'
        }
        if ($templatePath -and (Test-Path -LiteralPath $templatePath)) {
          $template = [IO.File]::ReadAllText($templatePath)
          $integration = $template.Replace('${dockerIntegrationTokenPlaceholder}', $script:StackBridgeDockerIntegrationToken)
          $integrationEncoded = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($integration))
          $contextText = $script:StackBridgeContext + $script:StackBridgeSeparator + "Docker: $selector"
          $contextEncoded = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($contextText))
          $wrappedArgs = @()
          for ($index = 0; $index -lt $dockerArgs.Count; $index++) {
            if ($index -eq $selectorIndex) {
              $wrappedArgs += @('-e', "STACKBRIDGE_CONTEXT_B64=$contextEncoded")
              $wrappedArgs += @('-e', "STACKBRIDGE_PROMPT_B64=$integrationEncoded")
              $wrappedArgs += @('-e', "STACKBRIDGE_TARGET_SHELL=$commandName")
              $wrappedArgs += $dockerArgs[$index]
            } elseif ($index -eq $commandIndex) {
              $wrappedArgs += @($commandName, '-c', $bootstrapCommand)
            } else {
              $wrappedArgs += $dockerArgs[$index]
            }
          }
          $preparedArgs = $wrappedArgs
        }
      }
      try { & $script:StackBridgeNativeDocker @preparedArgs }
      finally { if ($selector) { Send-StackBridgeEvent @{ type = 'environmentPop' } } }
      return
    }
    & $script:StackBridgeNativeDocker @dockerArgs
  }
}

Send-StackBridgeEvent @{
  type = 'prompt'
  cwd = [string]$executionContext.SessionState.Path.CurrentLocation
  shell = $(if ($PSVersionTable.PSEdition -eq 'Core') { 'pwsh' } else { 'powershell' })
  user = [Environment]::UserName
}
`.replaceAll("\\${", "${");
}

export function bashIntegrationScript(integrationToken: string): string {
  return String.raw`# StackBridge session-only Bash integration.
__sb_token='${integrationToken}'
if [[ -f "$HOME/.bashrc" && -z "\${STACKBRIDGE_BASHRC_LOADED:-}" ]]; then
  export STACKBRIDGE_BASHRC_LOADED=1
  source "$HOME/.bashrc"
fi

__sb_prompt_context="$(printf '%s' "\${STACKBRIDGE_CONTEXT_B64:-}" | base64 -d 2>/dev/null | tr -d '\000-\037\177')"
[[ -n "$__sb_prompt_context" ]] || __sb_prompt_context='${remoteShellFallbackLabel}'

__sb_json_escape() {
  local value="$1"
  value="\${value//\\/\\\\}"
  value="\${value//\"/\\\"}"
  value="\${value//$'\n'/\\n}"
  value="\${value//$'\r'/\\r}"
  value="\${value//$'\t'/\\t}"
  printf '%s' "$value"
}

__sb_emit_json() {
  local encoded
  encoded="$(printf '%s' "$1" | base64 | tr -d '\r\n' | tr '+/' '-_' | tr -d '=')"
  printf '\033]777;stackbridge;%s;%s\007' "$__sb_token" "$encoded"
}

__sb_print_context() {
  printf '\033[2;38;5;111m╭─[ %s ]\033[0m\r\n' "$__sb_prompt_context"
}

docker() {
  local -a docker_args=("$@")
  local -a wrapped_args=()
  local arg selector selector_json docker_status shell_program integration_file integration_encoded context_encoded bootstrap
  local saw_exec=0 expect_value=0 global_expect_value=0 container_prefix=0 invalid_command=0 interactive=0 tty=0 position=0 selector_position=-1 shell_extra=0
  for arg in "\${docker_args[@]}"; do
    (( position += 1 ))
    if [[ "$selector_position" -ge 0 ]]; then
      if [[ -z "$shell_program" ]]; then shell_program="$arg"; else shell_extra=1; fi
      continue
    fi
    if [[ "$saw_exec" != 1 ]]; then
      if [[ "$global_expect_value" == 1 ]]; then global_expect_value=0; continue; fi
      if [[ "$container_prefix" == 1 ]]; then
        if [[ "$arg" == exec ]]; then saw_exec=1; else invalid_command=1; break; fi
        continue
      fi
      case "$arg" in
        exec) saw_exec=1 ;;
        container) container_prefix=1 ;;
        -c|--context|--config|-H|--host|-l|--log-level) global_expect_value=1 ;;
        -*) ;;
        *) invalid_command=1; break ;;
      esac
      continue
    fi
    if [[ "$expect_value" == 1 ]]; then expect_value=0; continue; fi
    case "$arg" in
      -it|-ti) interactive=1; tty=1 ;;
      -i|--interactive) interactive=1 ;;
      -t|--tty) tty=1 ;;
      -u|--user|-w|--workdir|-e|--env|--env-file|--detach-keys) expect_value=1 ;;
      --) ;;
      -*) ;;
      *) selector="$arg"; selector_position="$position" ;;
    esac
  done
  if [[ "$saw_exec" == 1 && "$interactive" == 1 && "$tty" == 1 && -n "$selector" ]]; then
    selector_json="$(__sb_json_escape "$selector")"
    __sb_emit_json "{\"type\":\"environmentPush\",\"kind\":\"docker\",\"label\":\"Docker: $selector_json\"}"
    integration_file=''
    bootstrap=''
    if [[ "$shell_extra" == 0 ]]; then
      case "$shell_program" in
        bash|/bin/bash)
          integration_file="$HOME/.sbridge/shell/docker-bashrc"
          bootstrap='umask 077; runtime_dir="$(mktemp -d "\${TMPDIR:-/tmp}/stackbridge-shell.XXXXXX")" || exec "$STACKBRIDGE_TARGET_SHELL" -i; chmod 700 "$runtime_dir" || { rmdir "$runtime_dir"; exec "$STACKBRIDGE_TARGET_SHELL" -i; }; if ! printf %s "$STACKBRIDGE_PROMPT_B64" | base64 -d > "$runtime_dir/bashrc"; then rm -f "$runtime_dir/bashrc"; rmdir "$runtime_dir"; exec "$STACKBRIDGE_TARGET_SHELL" -i; fi; export STACKBRIDGE_EPHEMERAL_DIR="$runtime_dir"; unset STACKBRIDGE_PROMPT_B64; exec "$STACKBRIDGE_TARGET_SHELL" --rcfile "$runtime_dir/bashrc" -i'
          ;;
        zsh|/bin/zsh)
          integration_file="$HOME/.sbridge/shell/docker-zshrc"
          bootstrap='umask 077; runtime_dir="$(mktemp -d "\${TMPDIR:-/tmp}/stackbridge-shell.XXXXXX")" || exec "$STACKBRIDGE_TARGET_SHELL" -i; chmod 700 "$runtime_dir" || { rmdir "$runtime_dir"; exec "$STACKBRIDGE_TARGET_SHELL" -i; }; if ! printf %s "$STACKBRIDGE_PROMPT_B64" | base64 -d > "$runtime_dir/.zshrc"; then rm -f "$runtime_dir/.zshrc"; rmdir "$runtime_dir"; exec "$STACKBRIDGE_TARGET_SHELL" -i; fi; export STACKBRIDGE_EPHEMERAL_DIR="$runtime_dir"; unset STACKBRIDGE_PROMPT_B64; export STACKBRIDGE_USER_ZDOTDIR="\${ZDOTDIR-}"; export STACKBRIDGE_USER_ZDOTDIR_SET="\${ZDOTDIR+x}"; export ZDOTDIR="$runtime_dir"; exec "$STACKBRIDGE_TARGET_SHELL" -i'
          ;;
      esac
    fi
    if [[ -n "$integration_file" && -r "$integration_file" ]]; then
      integration_encoded="$(base64 < "$integration_file" | tr -d '\r\n')"
      context_encoded="$(printf '%s' "$__sb_prompt_context → Docker: $selector" | base64 | tr -d '\r\n')"
      position=0
      for arg in "\${docker_args[@]}"; do
        (( position += 1 ))
        if [[ "$position" == "$selector_position" ]]; then
          wrapped_args+=(-e "STACKBRIDGE_CONTEXT_B64=$context_encoded" -e "STACKBRIDGE_PROMPT_B64=$integration_encoded" -e "STACKBRIDGE_TARGET_SHELL=$shell_program" "$arg")
        elif [[ "$position" == "$((selector_position + 1))" ]]; then
          wrapped_args+=("$shell_program" -c "$bootstrap")
        else
          wrapped_args+=("$arg")
        fi
      done
      command docker "\${wrapped_args[@]}"
    else
      command docker "\${docker_args[@]}"
    fi
    docker_status=$?
    __sb_emit_json '{"type":"environmentPop"}'
    return "$docker_status"
  fi
  command docker "\${docker_args[@]}"
}

__sb_emit_prompt() {
  local cwd user
  cwd="$(__sb_json_escape "$PWD")"
  user="$(__sb_json_escape "$(id -un 2>/dev/null || printf unknown)")"
  __sb_emit_json "{\"type\":\"prompt\",\"cwd\":\"$cwd\",\"shell\":\"bash\",\"user\":\"$user\"}"
}

__sb_emit_start() {
  local command cwd user
  command="$(__sb_json_escape "$1")"
  cwd="$(__sb_json_escape "$PWD")"
  user="$(__sb_json_escape "$(id -un 2>/dev/null || printf unknown)")"
  __sb_emit_json "{\"type\":\"commandStart\",\"command\":\"$command\",\"cwd\":\"$cwd\",\"shell\":\"bash\",\"user\":\"$user\"}"
}

__sb_emit_end() {
  local cwd
  cwd="$(__sb_json_escape "$PWD")"
  __sb_emit_json "{\"type\":\"commandEnd\",\"cwd\":\"$cwd\",\"exitCode\":$1}"
}

__sb_guard=0
__sb_waiting_for_command=1
__sb_command_active=0

__sb_preexec() {
  [[ "$__sb_guard" == 1 || "$__sb_waiting_for_command" != 1 ]] && return
  __sb_guard=1
  __sb_waiting_for_command=0
  __sb_command_active=1
  local command
  command="$(history 1)"
  command="\${command#*[0-9]  }"
  __sb_emit_start "$command"
  __sb_guard=0
}

__sb_precmd() {
  local status=$?
  __sb_guard=1
  if [[ "$__sb_command_active" == 1 ]]; then __sb_emit_end "$status"; fi
  __sb_command_active=0
  __sb_emit_prompt
  __sb_print_context
  __sb_waiting_for_command=1
  __sb_guard=0
}

trap '__sb_preexec' DEBUG
PROMPT_COMMAND="__sb_precmd\${PROMPT_COMMAND:+;$PROMPT_COMMAND}"
`.replaceAll("\\${", "${");
}

export function zshIntegrationScript(integrationToken: string): string {
  return String.raw`# StackBridge session-only Zsh integration.
typeset -g __sb_token='${integrationToken}'
if [[ -n "\${STACKBRIDGE_USER_ZDOTDIR:-}" && -f "$STACKBRIDGE_USER_ZDOTDIR/.zshrc" ]]; then
  source "$STACKBRIDGE_USER_ZDOTDIR/.zshrc"
elif [[ -f "$HOME/.zshrc" ]]; then
  source "$HOME/.zshrc"
fi
autoload -Uz add-zsh-hook

typeset -g __sb_prompt_context="$(printf '%s' "\${STACKBRIDGE_CONTEXT_B64:-}" | base64 -d 2>/dev/null | tr -d '\000-\037\177')"
[[ -n "$__sb_prompt_context" ]] || typeset -g __sb_prompt_context='${remoteShellFallbackLabel}'

__sb_json_escape() {
  local value="$1"
  value="\${value//\\/\\\\}"
  value="\${value//\"/\\\"}"
  value="\${value//$'\n'/\\n}"
  value="\${value//$'\r'/\\r}"
  printf '%s' "$value"
}

__sb_emit_json() {
  local encoded="$(printf '%s' "$1" | base64 | tr -d '\r\n' | tr '+/' '-_' | tr -d '=')"
  printf '\033]777;stackbridge;%s;%s\007' "$__sb_token" "$encoded"
}

__sb_print_context() {
  printf '\033[2;38;5;111m╭─[ %s ]\033[0m\r\n' "$__sb_prompt_context"
}

docker() {
  local -a docker_args=("$@")
  local -a wrapped_args=()
  local arg selector selector_json docker_status shell_program integration_file integration_encoded context_encoded bootstrap
  local saw_exec=0 expect_value=0 global_expect_value=0 container_prefix=0 invalid_command=0 interactive=0 tty=0 position=0 selector_position=-1 shell_extra=0
  for arg in "\${docker_args[@]}"; do
    (( position += 1 ))
    if [[ "$selector_position" -ge 0 ]]; then
      if [[ -z "$shell_program" ]]; then shell_program="$arg"; else shell_extra=1; fi
      continue
    fi
    if [[ "$saw_exec" != 1 ]]; then
      if [[ "$global_expect_value" == 1 ]]; then global_expect_value=0; continue; fi
      if [[ "$container_prefix" == 1 ]]; then
        if [[ "$arg" == exec ]]; then saw_exec=1; else invalid_command=1; break; fi
        continue
      fi
      case "$arg" in
        exec) saw_exec=1 ;;
        container) container_prefix=1 ;;
        -c|--context|--config|-H|--host|-l|--log-level) global_expect_value=1 ;;
        -*) ;;
        *) invalid_command=1; break ;;
      esac
      continue
    fi
    if [[ "$expect_value" == 1 ]]; then expect_value=0; continue; fi
    case "$arg" in
      -it|-ti) interactive=1; tty=1 ;;
      -i|--interactive) interactive=1 ;;
      -t|--tty) tty=1 ;;
      -u|--user|-w|--workdir|-e|--env|--env-file|--detach-keys) expect_value=1 ;;
      --) ;;
      -*) ;;
      *) selector="$arg"; selector_position="$position" ;;
    esac
  done
  if [[ "$saw_exec" == 1 && "$interactive" == 1 && "$tty" == 1 && -n "$selector" ]]; then
    selector_json="$(__sb_json_escape "$selector")"
    __sb_emit_json "{\"type\":\"environmentPush\",\"kind\":\"docker\",\"label\":\"Docker: $selector_json\"}"
    integration_file=''
    bootstrap=''
    if [[ "$shell_extra" == 0 ]]; then
      case "$shell_program" in
        bash|/bin/bash)
          integration_file="$HOME/.sbridge/shell/docker-bashrc"
          bootstrap='umask 077; runtime_dir="$(mktemp -d "\${TMPDIR:-/tmp}/stackbridge-shell.XXXXXX")" || exec "$STACKBRIDGE_TARGET_SHELL" -i; chmod 700 "$runtime_dir" || { rmdir "$runtime_dir"; exec "$STACKBRIDGE_TARGET_SHELL" -i; }; if ! printf %s "$STACKBRIDGE_PROMPT_B64" | base64 -d > "$runtime_dir/bashrc"; then rm -f "$runtime_dir/bashrc"; rmdir "$runtime_dir"; exec "$STACKBRIDGE_TARGET_SHELL" -i; fi; export STACKBRIDGE_EPHEMERAL_DIR="$runtime_dir"; unset STACKBRIDGE_PROMPT_B64; exec "$STACKBRIDGE_TARGET_SHELL" --rcfile "$runtime_dir/bashrc" -i'
          ;;
        zsh|/bin/zsh)
          integration_file="$HOME/.sbridge/shell/docker-zshrc"
          bootstrap='umask 077; runtime_dir="$(mktemp -d "\${TMPDIR:-/tmp}/stackbridge-shell.XXXXXX")" || exec "$STACKBRIDGE_TARGET_SHELL" -i; chmod 700 "$runtime_dir" || { rmdir "$runtime_dir"; exec "$STACKBRIDGE_TARGET_SHELL" -i; }; if ! printf %s "$STACKBRIDGE_PROMPT_B64" | base64 -d > "$runtime_dir/.zshrc"; then rm -f "$runtime_dir/.zshrc"; rmdir "$runtime_dir"; exec "$STACKBRIDGE_TARGET_SHELL" -i; fi; export STACKBRIDGE_EPHEMERAL_DIR="$runtime_dir"; unset STACKBRIDGE_PROMPT_B64; export STACKBRIDGE_USER_ZDOTDIR="\${ZDOTDIR-}"; export STACKBRIDGE_USER_ZDOTDIR_SET="\${ZDOTDIR+x}"; export ZDOTDIR="$runtime_dir"; exec "$STACKBRIDGE_TARGET_SHELL" -i'
          ;;
      esac
    fi
    if [[ -n "$integration_file" && -r "$integration_file" ]]; then
      integration_encoded="$(base64 < "$integration_file" | tr -d '\r\n')"
      context_encoded="$(printf '%s' "$__sb_prompt_context → Docker: $selector" | base64 | tr -d '\r\n')"
      position=0
      for arg in "\${docker_args[@]}"; do
        (( position += 1 ))
        if [[ "$position" == "$selector_position" ]]; then
          wrapped_args+=(-e "STACKBRIDGE_CONTEXT_B64=$context_encoded" -e "STACKBRIDGE_PROMPT_B64=$integration_encoded" -e "STACKBRIDGE_TARGET_SHELL=$shell_program" "$arg")
        elif [[ "$position" == "$((selector_position + 1))" ]]; then
          wrapped_args+=("$shell_program" -c "$bootstrap")
        else
          wrapped_args+=("$arg")
        fi
      done
      command docker "\${wrapped_args[@]}"
    else
      command docker "\${docker_args[@]}"
    fi
    docker_status=$?
    __sb_emit_json '{"type":"environmentPop"}'
    return "$docker_status"
  fi
  command docker "\${docker_args[@]}"
}

__sb_preexec() {
  local command="$(__sb_json_escape "$1")"
  local cwd="$(__sb_json_escape "$PWD")"
  local user="$(__sb_json_escape "$(id -un 2>/dev/null || printf unknown)")"
  __sb_emit_json "{\"type\":\"commandStart\",\"command\":\"$command\",\"cwd\":\"$cwd\",\"shell\":\"zsh\",\"user\":\"$user\"}"
  typeset -g __sb_command_active=1
}

__sb_precmd() {
  local exit_status=$?
  local cwd="$(__sb_json_escape "$PWD")"
  local user="$(__sb_json_escape "$(id -un 2>/dev/null || printf unknown)")"
  if [[ "\${__sb_command_active:-0}" == 1 ]]; then
    __sb_emit_json "{\"type\":\"commandEnd\",\"cwd\":\"$cwd\",\"exitCode\":$exit_status}"
  fi
  typeset -g __sb_command_active=0
  __sb_emit_json "{\"type\":\"prompt\",\"cwd\":\"$cwd\",\"shell\":\"zsh\",\"user\":\"$user\"}"
  __sb_print_context
}

add-zsh-hook preexec __sb_preexec
add-zsh-hook precmd __sb_precmd
`.replaceAll("\\${", "${");
}

export function bashDockerPromptScript(integrationToken: string): string {
  return String.raw`# StackBridge command-scoped Docker Bash integration.
__sb_token='${integrationToken}'
if [[ -f "$HOME/.bashrc" && -z "\${STACKBRIDGE_BASHRC_LOADED:-}" ]]; then
  export STACKBRIDGE_BASHRC_LOADED=1
  source "$HOME/.bashrc"
fi

__sb_docker_prompt_context="$(printf '%s' "\${STACKBRIDGE_CONTEXT_B64:-}" | base64 -d 2>/dev/null | tr -d '\000-\037\177')"

__sb_docker_print_context() {
  [[ -n "$__sb_docker_prompt_context" ]] && printf '\033[2;38;5;111m╭─[ %s ]\033[0m\r\n' "$__sb_docker_prompt_context"
}

__sb_json_escape() {
  local value="$1"
  value="\${value//\\/\\\\}"
  value="\${value//\"/\\\"}"
  value="\${value//$'\n'/\\n}"
  value="\${value//$'\r'/\\r}"
  value="\${value//$'\t'/\\t}"
  printf '%s' "$value"
}

__sb_emit_json() {
  local encoded
  encoded="$(printf '%s' "$1" | base64 | tr -d '\r\n' | tr '+/' '-_' | tr -d '=')"
  printf '\033]777;stackbridge;%s;%s\007' "$__sb_token" "$encoded"
}

__sb_emit_prompt() {
  local cwd user
  cwd="$(__sb_json_escape "$PWD")"
  user="$(__sb_json_escape "$(id -un 2>/dev/null || printf unknown)")"
  __sb_emit_json "{\"type\":\"prompt\",\"cwd\":\"$cwd\",\"shell\":\"bash\",\"user\":\"$user\"}"
}

__sb_emit_start() {
  local command cwd user
  command="$(__sb_json_escape "$1")"
  cwd="$(__sb_json_escape "$PWD")"
  user="$(__sb_json_escape "$(id -un 2>/dev/null || printf unknown)")"
  __sb_emit_json "{\"type\":\"commandStart\",\"command\":\"$command\",\"cwd\":\"$cwd\",\"shell\":\"bash\",\"user\":\"$user\"}"
}

__sb_emit_end() {
  local cwd
  cwd="$(__sb_json_escape "$PWD")"
  __sb_emit_json "{\"type\":\"commandEnd\",\"cwd\":\"$cwd\",\"exitCode\":$1}"
}

if [[ -n "\${STACKBRIDGE_EPHEMERAL_DIR:-}" ]]; then
  rm -f -- "$STACKBRIDGE_EPHEMERAL_DIR/bashrc"
  rmdir -- "$STACKBRIDGE_EPHEMERAL_DIR" 2>/dev/null || true
  unset STACKBRIDGE_EPHEMERAL_DIR
fi

__sb_guard=0
__sb_waiting_for_command=1
__sb_command_active=0

__sb_preexec() {
  [[ "$__sb_guard" == 1 || "$__sb_waiting_for_command" != 1 ]] && return
  __sb_guard=1
  __sb_waiting_for_command=0
  __sb_command_active=1
  local command
  command="$(history 1)"
  command="\${command#*[0-9]  }"
  __sb_emit_start "$command"
  __sb_guard=0
}

__sb_precmd() {
  local status=$?
  __sb_guard=1
  if [[ "$__sb_command_active" == 1 ]]; then __sb_emit_end "$status"; fi
  __sb_command_active=0
  __sb_emit_prompt
  __sb_docker_print_context
  __sb_waiting_for_command=1
  __sb_guard=0
}

trap '__sb_preexec' DEBUG
PROMPT_COMMAND="__sb_precmd\${PROMPT_COMMAND:+;$PROMPT_COMMAND}"
`.replaceAll("\\${", "${");
}

export function zshDockerPromptScript(integrationToken: string): string {
  return String.raw`# StackBridge command-scoped Docker Zsh integration.
typeset -g __sb_token='${integrationToken}'
if [[ -n "\${STACKBRIDGE_USER_ZDOTDIR:-}" && -f "$STACKBRIDGE_USER_ZDOTDIR/.zshrc" ]]; then
  source "$STACKBRIDGE_USER_ZDOTDIR/.zshrc"
elif [[ -f "$HOME/.zshrc" ]]; then
  source "$HOME/.zshrc"
fi
autoload -Uz add-zsh-hook

typeset -g __sb_docker_prompt_context="$(printf '%s' "\${STACKBRIDGE_CONTEXT_B64:-}" | base64 -d 2>/dev/null | tr -d '\000-\037\177')"

__sb_docker_print_context() {
  [[ -n "$__sb_docker_prompt_context" ]] && printf '\033[2;38;5;111m╭─[ %s ]\033[0m\r\n' "$__sb_docker_prompt_context"
}

__sb_json_escape() {
  local value="$1"
  value="\${value//\\/\\\\}"
  value="\${value//\"/\\\"}"
  value="\${value//$'\n'/\\n}"
  value="\${value//$'\r'/\\r}"
  printf '%s' "$value"
}

__sb_emit_json() {
  local encoded="$(printf '%s' "$1" | base64 | tr -d '\r\n' | tr '+/' '-_' | tr -d '=')"
  printf '\033]777;stackbridge;%s;%s\007' "$__sb_token" "$encoded"
}

if [[ -n "\${STACKBRIDGE_EPHEMERAL_DIR:-}" ]]; then
  rm -f -- "$STACKBRIDGE_EPHEMERAL_DIR/.zshrc"
  rmdir -- "$STACKBRIDGE_EPHEMERAL_DIR" 2>/dev/null || true
  unset STACKBRIDGE_EPHEMERAL_DIR
fi

if [[ "\${STACKBRIDGE_USER_ZDOTDIR_SET:-}" == 1 ]]; then
  export ZDOTDIR="$STACKBRIDGE_USER_ZDOTDIR"
else
  unset ZDOTDIR
fi
unset STACKBRIDGE_USER_ZDOTDIR STACKBRIDGE_USER_ZDOTDIR_SET

__sb_preexec() {
  local command="$(__sb_json_escape "$1")"
  local cwd="$(__sb_json_escape "$PWD")"
  local user="$(__sb_json_escape "$(id -un 2>/dev/null || printf unknown)")"
  __sb_emit_json "{\"type\":\"commandStart\",\"command\":\"$command\",\"cwd\":\"$cwd\",\"shell\":\"zsh\",\"user\":\"$user\"}"
  typeset -g __sb_command_active=1
}

__sb_precmd() {
  local exit_status=$?
  local cwd="$(__sb_json_escape "$PWD")"
  local user="$(__sb_json_escape "$(id -un 2>/dev/null || printf unknown)")"
  if [[ "\${__sb_command_active:-0}" == 1 ]]; then
    __sb_emit_json "{\"type\":\"commandEnd\",\"cwd\":\"$cwd\",\"exitCode\":$exit_status}"
  fi
  typeset -g __sb_command_active=0
  __sb_emit_json "{\"type\":\"prompt\",\"cwd\":\"$cwd\",\"shell\":\"zsh\",\"user\":\"$user\"}"
  __sb_docker_print_context
}

add-zsh-hook preexec __sb_preexec
add-zsh-hook precmd __sb_precmd
`.replaceAll("\\${", "${");
}
