import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const integrationFileName = "powershell-integration.ps1";

export function ensurePowerShellIntegration(dataDirectory: string): string {
  const shellDirectory = join(dataDirectory, "shell");
  mkdirSync(shellDirectory, { recursive: true, mode: 0o700 });
  const integrationPath = join(shellDirectory, integrationFileName);
  writeFileSync(integrationPath, powerShellIntegrationScript(), {
    encoding: "utf8",
    mode: 0o600,
  });
  return integrationPath;
}

export function powerShellIntegrationScript(): string {
  return String.raw`# StackBridge session-only shell integration. This file is regenerated by Core.
param([Parameter(Mandatory=$true)][string]$StackBridgeIntegrationToken)
$script:StackBridgeIntegrationToken = $StackBridgeIntegrationToken
$script:StackBridgeCommandActive = $false
$script:StackBridgeNativeSsh = Get-Command ssh.exe -ErrorAction SilentlyContinue
$script:StackBridgeNativeDocker = Get-Command docker.exe -ErrorAction SilentlyContinue

function global:Send-StackBridgeEvent {
  param([Parameter(Mandatory=$true)][hashtable]$Event)
  try {
    $json = $Event | ConvertTo-Json -Compress -Depth 8
    $bytes = [Text.Encoding]::UTF8.GetBytes($json)
    $encoded = [Convert]::ToBase64String($bytes).TrimEnd('=').Replace('+', '-').Replace('/', '_')
    [Console]::Write("$([char]27)]777;stackbridge;$script:StackBridgeIntegrationToken;$encoded$([char]7)")
  } catch {}
}

function global:prompt {
  $succeeded = $?
  if ($script:StackBridgeCommandActive) {
    Send-StackBridgeEvent @{
      type = 'commandEnd'
      cwd = [string]$executionContext.SessionState.Path.CurrentLocation
      exitCode = $(if ($succeeded) { 0 } else { 1 })
    }
    $script:StackBridgeCommandActive = $false
  }
  Send-StackBridgeEvent @{
    type = 'prompt'
    cwd = [string]$executionContext.SessionState.Path.CurrentLocation
    shell = $(if ($PSVersionTable.PSEdition -eq 'Core') { 'pwsh' } else { 'powershell' })
    user = [Environment]::UserName
  }
  "PS $($executionContext.SessionState.Path.CurrentLocation)> "
}

if (Get-Module -ListAvailable -Name PSReadLine) {
  Import-Module PSReadLine -ErrorAction SilentlyContinue
  Set-PSReadLineOption -AddToHistoryHandler {
    param([string]$line)
    Send-StackBridgeEvent @{
      type = 'commandStart'
      command = $line
      cwd = [string]$executionContext.SessionState.Path.CurrentLocation
      shell = $(if ($PSVersionTable.PSEdition -eq 'Core') { 'pwsh' } else { 'powershell' })
      user = [Environment]::UserName
    }
    $script:StackBridgeCommandActive = $true
    return $true
  }
}

if ($script:StackBridgeNativeSsh) {
  function global:ssh {
    $displayTarget = ($args | Where-Object { $_ -is [string] -and -not $_.StartsWith('-') } | Select-Object -Last 1)
    if (-not $displayTarget) { $displayTarget = ($args -join ' ') }
    Send-StackBridgeEvent @{
      type = 'environmentPush'
      kind = 'ssh'
      label = "SSH: $displayTarget"
      host = [string]$displayTarget
      verified = $false
    }
    try { & $script:StackBridgeNativeSsh @args }
    finally { Send-StackBridgeEvent @{ type = 'environmentPop' } }
  }
}

if ($script:StackBridgeNativeDocker) {
  function global:docker {
    $dockerArgs = @($args)
    $execIndex = [Array]::IndexOf($dockerArgs, 'exec')
    $interactive = $dockerArgs -contains '-it' -or $dockerArgs -contains '-ti' -or (($dockerArgs -contains '-i') -and ($dockerArgs -contains '-t'))
    if ($execIndex -ge 0 -and $interactive) {
      $selector = $null
      for ($index = $execIndex + 1; $index -lt $dockerArgs.Count; $index++) {
        $value = [string]$dockerArgs[$index]
        if ($value -in @('-i', '-t', '-it', '-ti')) { continue }
        if ($value -in @('-u', '--user', '-w', '--workdir', '-e', '--env')) { $index++; continue }
        if ($value.StartsWith('-')) { continue }
        $selector = $value
        break
      }
      if ($selector) {
        Send-StackBridgeEvent @{
          type = 'environmentPush'
          kind = 'docker'
          label = "Docker: $selector"
          verified = $false
        }
      }
      try { & $script:StackBridgeNativeDocker @dockerArgs }
      finally { if ($selector) { Send-StackBridgeEvent @{ type = 'environmentPop' } } }
      return
    }
    & $script:StackBridgeNativeDocker @dockerArgs
  }
}

Send-StackBridgeEvent @{
  type = 'prompt'
  cwd = [string]$executionContext.SessionState.Path.CurrentLocation
  shell = $(if ($PSVersionTable.PSEdition -eq 'Core') { 'pwsh' } else { 'powershell' })
  user = [Environment]::UserName
}
`;
}

export function bashIntegrationScript(integrationToken: string): string {
  return String.raw`# StackBridge session-only Bash integration.
__sb_token='${integrationToken}'
if [[ -f "$HOME/.bashrc" && -z "\${STACKBRIDGE_BASHRC_LOADED:-}" ]]; then
  export STACKBRIDGE_BASHRC_LOADED=1
  source "$HOME/.bashrc"
fi

__sb_json_escape() {
  local value="$1"
  value="\${value//\\/\\\\}"
  value="\${value//\"/\\\"}"
  value="\${value//$'\n'/\\n}"
  value="\${value//$'\r'/\\r}"
  value="\${value//$'\t'/\\t}"
  printf '%s' "$value"
}

__sb_emit_json() {
  local encoded
  encoded="$(printf '%s' "$1" | base64 | tr -d '\r\n' | tr '+/' '-_' | tr -d '=')"
  printf '\033]777;stackbridge;%s;%s\007' "$__sb_token" "$encoded"
}

__sb_emit_prompt() {
  local cwd user
  cwd="$(__sb_json_escape "$PWD")"
  user="$(__sb_json_escape "$(id -un 2>/dev/null || printf unknown)")"
  __sb_emit_json "{\"type\":\"prompt\",\"cwd\":\"$cwd\",\"shell\":\"bash\",\"user\":\"$user\"}"
}

__sb_emit_start() {
  local command cwd user
  command="$(__sb_json_escape "$1")"
  cwd="$(__sb_json_escape "$PWD")"
  user="$(__sb_json_escape "$(id -un 2>/dev/null || printf unknown)")"
  __sb_emit_json "{\"type\":\"commandStart\",\"command\":\"$command\",\"cwd\":\"$cwd\",\"shell\":\"bash\",\"user\":\"$user\"}"
}

__sb_emit_end() {
  local cwd
  cwd="$(__sb_json_escape "$PWD")"
  __sb_emit_json "{\"type\":\"commandEnd\",\"cwd\":\"$cwd\",\"exitCode\":$1}"
}

__sb_guard=0
__sb_waiting_for_command=1
__sb_command_active=0

__sb_preexec() {
  [[ "$__sb_guard" == 1 || "$__sb_waiting_for_command" != 1 ]] && return
  __sb_guard=1
  __sb_waiting_for_command=0
  __sb_command_active=1
  local command
  command="$(history 1)"
  command="\${command#*[0-9]  }"
  __sb_emit_start "$command"
  __sb_guard=0
}

__sb_precmd() {
  local status=$?
  __sb_guard=1
  if [[ "$__sb_command_active" == 1 ]]; then __sb_emit_end "$status"; fi
  __sb_command_active=0
  __sb_emit_prompt
  __sb_waiting_for_command=1
  __sb_guard=0
}

trap '__sb_preexec' DEBUG
PROMPT_COMMAND="__sb_precmd\${PROMPT_COMMAND:+;$PROMPT_COMMAND}"
`.replaceAll("\\${", "${");
}

export function zshIntegrationScript(integrationToken: string): string {
  return String.raw`# StackBridge session-only Zsh integration.
typeset -g __sb_token='${integrationToken}'
if [[ -n "\${STACKBRIDGE_USER_ZDOTDIR:-}" && -f "$STACKBRIDGE_USER_ZDOTDIR/.zshrc" ]]; then
  source "$STACKBRIDGE_USER_ZDOTDIR/.zshrc"
elif [[ -f "$HOME/.zshrc" ]]; then
  source "$HOME/.zshrc"
fi
autoload -Uz add-zsh-hook

__sb_json_escape() {
  local value="$1"
  value="\${value//\\/\\\\}"
  value="\${value//\"/\\\"}"
  value="\${value//$'\n'/\\n}"
  value="\${value//$'\r'/\\r}"
  printf '%s' "$value"
}

__sb_emit_json() {
  local encoded="$(printf '%s' "$1" | base64 | tr -d '\r\n' | tr '+/' '-_' | tr -d '=')"
  printf '\033]777;stackbridge;%s;%s\007' "$__sb_token" "$encoded"
}

__sb_preexec() {
  local command="$(__sb_json_escape "$1")"
  local cwd="$(__sb_json_escape "$PWD")"
  local user="$(__sb_json_escape "$(id -un 2>/dev/null || printf unknown)")"
  __sb_emit_json "{\"type\":\"commandStart\",\"command\":\"$command\",\"cwd\":\"$cwd\",\"shell\":\"zsh\",\"user\":\"$user\"}"
  typeset -g __sb_command_active=1
}

__sb_precmd() {
  local exit_status=$?
  local cwd="$(__sb_json_escape "$PWD")"
  local user="$(__sb_json_escape "$(id -un 2>/dev/null || printf unknown)")"
  if [[ "\${__sb_command_active:-0}" == 1 ]]; then
    __sb_emit_json "{\"type\":\"commandEnd\",\"cwd\":\"$cwd\",\"exitCode\":$exit_status}"
  fi
  typeset -g __sb_command_active=0
  __sb_emit_json "{\"type\":\"prompt\",\"cwd\":\"$cwd\",\"shell\":\"zsh\",\"user\":\"$user\"}"
}

add-zsh-hook preexec __sb_preexec
add-zsh-hook precmd __sb_precmd
`.replaceAll("\\${", "${");
}
