import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const integrationFileName = "powershell-integration.ps1";
const bashIntegrationTemplateFileName = "bashrc.template";
const zshIntegrationTemplateFileName = "zshrc.template";
const integrationTokenPlaceholder = "__STACKBRIDGE_SESSION_TOKEN__";

export function ensurePowerShellIntegration(dataDirectory: string): string {
  const shellDirectory = join(dataDirectory, "shell");
  mkdirSync(shellDirectory, { recursive: true, mode: 0o700 });
  const integrationPath = join(shellDirectory, integrationFileName);
  writeFileSync(integrationPath, powerShellIntegrationScript(), {
    encoding: "utf8",
    mode: 0o600,
  });
  writeFileSync(
    join(shellDirectory, bashIntegrationTemplateFileName),
    bashIntegrationScript(integrationTokenPlaceholder),
    { encoding: "utf8", mode: 0o600 },
  );
  writeFileSync(
    join(shellDirectory, zshIntegrationTemplateFileName),
    zshIntegrationScript(integrationTokenPlaceholder),
    { encoding: "utf8", mode: 0o600 },
  );
  return integrationPath;
}

export function powerShellIntegrationScript(): string {
  return String.raw`# StackBridge session-only shell integration. This file is regenerated by Core.
param([Parameter(Mandatory=$true)][string]$StackBridgeIntegrationToken)
$script:StackBridgeIntegrationToken = $StackBridgeIntegrationToken
$script:StackBridgeCommandActive = $false
$script:StackBridgeNativeSsh = Get-Command ssh.exe -ErrorAction SilentlyContinue
$script:StackBridgeNativeDocker = Get-Command docker.exe -ErrorAction SilentlyContinue
$script:StackBridgeBashTemplate = Join-Path $PSScriptRoot '${bashIntegrationTemplateFileName}'
$script:StackBridgeZshTemplate = Join-Path $PSScriptRoot '${zshIntegrationTemplateFileName}'

function global:Send-StackBridgeEvent {
  param([Parameter(Mandatory=$true)][hashtable]$Event)
  try {
    $json = $Event | ConvertTo-Json -Compress -Depth 8
    $bytes = [Text.Encoding]::UTF8.GetBytes($json)
    $encoded = [Convert]::ToBase64String($bytes).TrimEnd('=').Replace('+', '-').Replace('/', '_')
    [Console]::Write("$([char]27)]777;stackbridge;$script:StackBridgeIntegrationToken;$encoded$([char]7)")
  } catch {}
}

function global:prompt {
  $succeeded = $?
  if ($script:StackBridgeCommandActive) {
    Send-StackBridgeEvent @{
      type = 'commandEnd'
      cwd = [string]$executionContext.SessionState.Path.CurrentLocation
      exitCode = $(if ($succeeded) { 0 } else { 1 })
    }
    $script:StackBridgeCommandActive = $false
  }
  Send-StackBridgeEvent @{
    type = 'prompt'
    cwd = [string]$executionContext.SessionState.Path.CurrentLocation
    shell = $(if ($PSVersionTable.PSEdition -eq 'Core') { 'pwsh' } else { 'powershell' })
    user = [Environment]::UserName
  }
  "PS $($executionContext.SessionState.Path.CurrentLocation)> "
}

if (Get-Module -ListAvailable -Name PSReadLine) {
  Import-Module PSReadLine -ErrorAction SilentlyContinue
  Set-PSReadLineOption -AddToHistoryHandler {
    param([string]$line)
    Send-StackBridgeEvent @{
      type = 'commandStart'
      command = $line
      cwd = [string]$executionContext.SessionState.Path.CurrentLocation
      shell = $(if ($PSVersionTable.PSEdition -eq 'Core') { 'pwsh' } else { 'powershell' })
      user = [Environment]::UserName
    }
    $script:StackBridgeCommandActive = $true
    return $true
  }
}

function Get-StackBridgeSshShape {
  param([Parameter(Mandatory=$true)][object[]]$ArgumentList)
  $optionsWithValue = @(
    '-B', '-b', '-c', '-D', '-E', '-e', '-F', '-I', '-i', '-J', '-L', '-l',
    '-m', '-O', '-o', '-p', '-Q', '-R', '-S', '-W', '-w'
  )
  $destinationIndex = -1
  $skipNext = $false
  for ($index = 0; $index -lt $ArgumentList.Count; $index++) {
    $value = [string]$ArgumentList[$index]
    if ($skipNext) { $skipNext = $false; continue }
    if ($value -eq '--' -and $index + 1 -lt $ArgumentList.Count) {
      $destinationIndex = $index + 1
      break
    }
    if ($value.StartsWith('-')) {
      if ($optionsWithValue -contains $value) { $skipNext = $true }
      continue
    }
    $destinationIndex = $index
    break
  }
  if ($destinationIndex -lt 0) {
    return @{ Destination = $null; Interactive = $false }
  }
  return @{
    Destination = [string]$ArgumentList[$destinationIndex]
    Interactive = ($destinationIndex -eq $ArgumentList.Count - 1)
  }
}

function Install-StackBridgeRemoteShellIntegration {
  param([Parameter(Mandatory=$true)][object[]]$SshArguments)
  if (-not (Test-Path -LiteralPath $script:StackBridgeBashTemplate) -or
      -not (Test-Path -LiteralPath $script:StackBridgeZshTemplate)) {
    return $false
  }
  try {
    $bashTemplate = [IO.File]::ReadAllText($script:StackBridgeBashTemplate)
    $zshTemplate = [IO.File]::ReadAllText($script:StackBridgeZshTemplate)
    $bashScript = $bashTemplate.Replace('${integrationTokenPlaceholder}', $script:StackBridgeIntegrationToken)
    $zshScript = $zshTemplate.Replace('${integrationTokenPlaceholder}', $script:StackBridgeIntegrationToken)
    $bashEncoded = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($bashScript))
    $zshEncoded = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($zshScript))
    $installCommand = 'umask 077; mkdir -p "$HOME/.sbridge/shell" && printf %s ''' +
      $bashEncoded + ''' | base64 -d > "$HOME/.sbridge/shell/bashrc" && printf %s ''' +
      $zshEncoded + ''' | base64 -d > "$HOME/.sbridge/shell/.zshrc"'
    & $script:StackBridgeNativeSsh @SshArguments $installCommand
    return $LASTEXITCODE -eq 0
  } catch {
    return $false
  }
}

if ($script:StackBridgeNativeSsh) {
  function global:ssh {
    $sshArgs = @($args)
    $shape = Get-StackBridgeSshShape -ArgumentList $sshArgs
    $displayTarget = $shape.Destination
    if (-not $displayTarget) { $displayTarget = ($sshArgs -join ' ') }
    Send-StackBridgeEvent @{
      type = 'environmentPush'
      kind = 'ssh'
      label = "SSH: $displayTarget"
      host = [string]$displayTarget
      verified = $false
    }
    try {
      if (-not $shape.Interactive) {
        & $script:StackBridgeNativeSsh @sshArgs
        return
      }
      if (-not (Install-StackBridgeRemoteShellIntegration -SshArguments $sshArgs)) {
        & $script:StackBridgeNativeSsh @sshArgs
        return
      }
      $launchCommand = 'if [ "\${SHELL##*/}" = "zsh" ] && command -v zsh >/dev/null 2>&1; then export STACKBRIDGE_USER_ZDOTDIR="\${ZDOTDIR:-$HOME}"; export ZDOTDIR="$HOME/.sbridge/shell"; exec zsh -i; elif command -v bash >/dev/null 2>&1; then exec bash --rcfile "$HOME/.sbridge/shell/bashrc" -i; else exec "\${SHELL:-/bin/sh}" -i; fi'
      $interactiveArgs = @('-tt') + $sshArgs
      & $script:StackBridgeNativeSsh @interactiveArgs $launchCommand
    }
    finally { Send-StackBridgeEvent @{ type = 'environmentPop' } }
  }
}

if ($script:StackBridgeNativeDocker) {
  function global:docker {
    $dockerArgs = @($args)
    $execIndex = [Array]::IndexOf($dockerArgs, 'exec')
    $interactive = $dockerArgs -contains '-it' -or $dockerArgs -contains '-ti' -or (($dockerArgs -contains '-i') -and ($dockerArgs -contains '-t'))
    if ($execIndex -ge 0 -and $interactive) {
      $selector = $null
      for ($index = $execIndex + 1; $index -lt $dockerArgs.Count; $index++) {
        $value = [string]$dockerArgs[$index]
        if ($value -in @('-i', '-t', '-it', '-ti')) { continue }
        if ($value -in @('-u', '--user', '-w', '--workdir', '-e', '--env')) { $index++; continue }
        if ($value.StartsWith('-')) { continue }
        $selector = $value
        break
      }
      if ($selector) {
        Send-StackBridgeEvent @{
          type = 'environmentPush'
          kind = 'docker'
          label = "Docker: $selector"
          verified = $false
        }
      }
      try { & $script:StackBridgeNativeDocker @dockerArgs }
      finally { if ($selector) { Send-StackBridgeEvent @{ type = 'environmentPop' } } }
      return
    }
    & $script:StackBridgeNativeDocker @dockerArgs
  }
}

Send-StackBridgeEvent @{
  type = 'prompt'
  cwd = [string]$executionContext.SessionState.Path.CurrentLocation
  shell = $(if ($PSVersionTable.PSEdition -eq 'Core') { 'pwsh' } else { 'powershell' })
  user = [Environment]::UserName
}
`.replaceAll("\\${", "${");
}

export function bashIntegrationScript(integrationToken: string): string {
  return String.raw`# StackBridge session-only Bash integration.
__sb_token='${integrationToken}'
if [[ -f "$HOME/.bashrc" && -z "\${STACKBRIDGE_BASHRC_LOADED:-}" ]]; then
  export STACKBRIDGE_BASHRC_LOADED=1
  source "$HOME/.bashrc"
fi

__sb_json_escape() {
  local value="$1"
  value="\${value//\\/\\\\}"
  value="\${value//\"/\\\"}"
  value="\${value//$'\n'/\\n}"
  value="\${value//$'\r'/\\r}"
  value="\${value//$'\t'/\\t}"
  printf '%s' "$value"
}

__sb_emit_json() {
  local encoded
  encoded="$(printf '%s' "$1" | base64 | tr -d '\r\n' | tr '+/' '-_' | tr -d '=')"
  printf '\033]777;stackbridge;%s;%s\007' "$__sb_token" "$encoded"
}

docker() {
  local -a docker_args=("$@")
  local arg selector selector_json docker_status
  local saw_exec=0 expect_value=0 interactive=0 tty=0
  for arg in "\${docker_args[@]}"; do
    if [[ "$saw_exec" != 1 ]]; then
      [[ "$arg" == exec ]] && saw_exec=1
      continue
    fi
    if [[ "$expect_value" == 1 ]]; then expect_value=0; continue; fi
    case "$arg" in
      -it|-ti) interactive=1; tty=1 ;;
      -i|--interactive) interactive=1 ;;
      -t|--tty) tty=1 ;;
      -u|--user|-w|--workdir|-e|--env|--env-file|--detach-keys) expect_value=1 ;;
      --) ;;
      -*) ;;
      *) selector="$arg"; break ;;
    esac
  done
  if [[ "$saw_exec" == 1 && "$interactive" == 1 && "$tty" == 1 && -n "$selector" ]]; then
    selector_json="$(__sb_json_escape "$selector")"
    __sb_emit_json "{\"type\":\"environmentPush\",\"kind\":\"docker\",\"label\":\"Docker: $selector_json\"}"
    command docker "\${docker_args[@]}"
    docker_status=$?
    __sb_emit_json '{"type":"environmentPop"}'
    return "$docker_status"
  fi
  command docker "\${docker_args[@]}"
}

__sb_emit_prompt() {
  local cwd user
  cwd="$(__sb_json_escape "$PWD")"
  user="$(__sb_json_escape "$(id -un 2>/dev/null || printf unknown)")"
  __sb_emit_json "{\"type\":\"prompt\",\"cwd\":\"$cwd\",\"shell\":\"bash\",\"user\":\"$user\"}"
}

__sb_emit_start() {
  local command cwd user
  command="$(__sb_json_escape "$1")"
  cwd="$(__sb_json_escape "$PWD")"
  user="$(__sb_json_escape "$(id -un 2>/dev/null || printf unknown)")"
  __sb_emit_json "{\"type\":\"commandStart\",\"command\":\"$command\",\"cwd\":\"$cwd\",\"shell\":\"bash\",\"user\":\"$user\"}"
}

__sb_emit_end() {
  local cwd
  cwd="$(__sb_json_escape "$PWD")"
  __sb_emit_json "{\"type\":\"commandEnd\",\"cwd\":\"$cwd\",\"exitCode\":$1}"
}

__sb_guard=0
__sb_waiting_for_command=1
__sb_command_active=0

__sb_preexec() {
  [[ "$__sb_guard" == 1 || "$__sb_waiting_for_command" != 1 ]] && return
  __sb_guard=1
  __sb_waiting_for_command=0
  __sb_command_active=1
  local command
  command="$(history 1)"
  command="\${command#*[0-9]  }"
  __sb_emit_start "$command"
  __sb_guard=0
}

__sb_precmd() {
  local status=$?
  __sb_guard=1
  if [[ "$__sb_command_active" == 1 ]]; then __sb_emit_end "$status"; fi
  __sb_command_active=0
  __sb_emit_prompt
  __sb_waiting_for_command=1
  __sb_guard=0
}

trap '__sb_preexec' DEBUG
PROMPT_COMMAND="__sb_precmd\${PROMPT_COMMAND:+;$PROMPT_COMMAND}"
`.replaceAll("\\${", "${");
}

export function zshIntegrationScript(integrationToken: string): string {
  return String.raw`# StackBridge session-only Zsh integration.
typeset -g __sb_token='${integrationToken}'
if [[ -n "\${STACKBRIDGE_USER_ZDOTDIR:-}" && -f "$STACKBRIDGE_USER_ZDOTDIR/.zshrc" ]]; then
  source "$STACKBRIDGE_USER_ZDOTDIR/.zshrc"
elif [[ -f "$HOME/.zshrc" ]]; then
  source "$HOME/.zshrc"
fi
autoload -Uz add-zsh-hook

__sb_json_escape() {
  local value="$1"
  value="\${value//\\/\\\\}"
  value="\${value//\"/\\\"}"
  value="\${value//$'\n'/\\n}"
  value="\${value//$'\r'/\\r}"
  printf '%s' "$value"
}

__sb_emit_json() {
  local encoded="$(printf '%s' "$1" | base64 | tr -d '\r\n' | tr '+/' '-_' | tr -d '=')"
  printf '\033]777;stackbridge;%s;%s\007' "$__sb_token" "$encoded"
}

docker() {
  local -a docker_args=("$@")
  local arg selector selector_json docker_status
  local saw_exec=0 expect_value=0 interactive=0 tty=0
  for arg in "\${docker_args[@]}"; do
    if [[ "$saw_exec" != 1 ]]; then
      [[ "$arg" == exec ]] && saw_exec=1
      continue
    fi
    if [[ "$expect_value" == 1 ]]; then expect_value=0; continue; fi
    case "$arg" in
      -it|-ti) interactive=1; tty=1 ;;
      -i|--interactive) interactive=1 ;;
      -t|--tty) tty=1 ;;
      -u|--user|-w|--workdir|-e|--env|--env-file|--detach-keys) expect_value=1 ;;
      --) ;;
      -*) ;;
      *) selector="$arg"; break ;;
    esac
  done
  if [[ "$saw_exec" == 1 && "$interactive" == 1 && "$tty" == 1 && -n "$selector" ]]; then
    selector_json="$(__sb_json_escape "$selector")"
    __sb_emit_json "{\"type\":\"environmentPush\",\"kind\":\"docker\",\"label\":\"Docker: $selector_json\"}"
    command docker "\${docker_args[@]}"
    docker_status=$?
    __sb_emit_json '{"type":"environmentPop"}'
    return "$docker_status"
  fi
  command docker "\${docker_args[@]}"
}

__sb_preexec() {
  local command="$(__sb_json_escape "$1")"
  local cwd="$(__sb_json_escape "$PWD")"
  local user="$(__sb_json_escape "$(id -un 2>/dev/null || printf unknown)")"
  __sb_emit_json "{\"type\":\"commandStart\",\"command\":\"$command\",\"cwd\":\"$cwd\",\"shell\":\"zsh\",\"user\":\"$user\"}"
  typeset -g __sb_command_active=1
}

__sb_precmd() {
  local exit_status=$?
  local cwd="$(__sb_json_escape "$PWD")"
  local user="$(__sb_json_escape "$(id -un 2>/dev/null || printf unknown)")"
  if [[ "\${__sb_command_active:-0}" == 1 ]]; then
    __sb_emit_json "{\"type\":\"commandEnd\",\"cwd\":\"$cwd\",\"exitCode\":$exit_status}"
  fi
  typeset -g __sb_command_active=0
  __sb_emit_json "{\"type\":\"prompt\",\"cwd\":\"$cwd\",\"shell\":\"zsh\",\"user\":\"$user\"}"
}

add-zsh-hook preexec __sb_preexec
add-zsh-hook precmd __sb_precmd
`.replaceAll("\\${", "${");
}
